version: '3.8'

services:
  # Твой бэкенд (Go-приложение)
  app:
    build: .
    container_name: todo-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_URL: "postgres://postgres:01131@toDoList:5432/to_do?sslmode=disable"
    depends_on:
      - toDoList

  toDoList:
    image: postgres:15-alpine
    container_name: toDoList
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 01131
      POSTGRES_DB: to_do
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

volumes:
  pgdata: